name: madness-portfolio CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true   # Évite les builds inutiles → bonne pratique RSE

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Récupère le code source

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
        # Configure Node.js v22 et active le cache npm (optimisation RSE)

      - name: Upgrade to npm v11
        run: npm install -g npm@11
        # Met à jour npm à la dernière version stable

      - name: Install dependencies
        run: npm ci
        # Installe les dépendances (rapide et reproductible)

      - name: Build project (Vite)
        run: npm run build
        # Compile ton projet pour la production


  Testing:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Upgrade to npm v11
        run: npm install -g npm@11

      - name: Install dependencies
        run: npm ci

#      - name: Run unit tests
#        run: npm test
        # Exécute tes tests unitaires (ex: Jest, Vitest)

      - name: Run linting (Code quality)
        run: npm run lint
        # Vérifie la qualité du code → maintenabilité (bonne pratique dev)

      - name: Accessibility tests (a11y)
        run: npx pa11y http://localhost:4173 || true
        # Vérifie l’accessibilité → inclusion utilisateur


  Performance:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Upgrade to npm v11
        run: npm install -g npm@11

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

#      - name: Run Lighthouse CI
#        run: lhci autorun
        # Analyse performance, accessibilité, SEO et bonnes pratiques
